---
# site.yml for testbuild-ocp

- name: Project testbuild-ocp
  hosts: all
  gather_facts: no

  tasks:
  - name: some role
    include_role:
      name: some role
      apply:
        tags:
          - some tag
    vars:
      # add variables if needed else delete entire section
    tags:
      - always